name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

#      - name: Generate Rust client from OpenAPI
#        run: |
#          docker run --rm \
#            -v ${{ github.workspace }}/public/openapi-spec:/openapi-spec \
#            -v ${{ github.workspace }}/external:/external \
#            openapitools/openapi-generator-cli:latest generate \
#            -g rust \
#            -i /openapi-spec/service-openapi.yaml \
#            -o /external

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Format code
        run: cargo fmt -- --check
